# GitHub Actions: Build ESP8266 Firmware (Arduino) + Notify Devices via MQTT
#
# TRIGGER: push a version tag → v1.0.0, v1.1.0, etc.
#
# FLOW:
#   1. Arduino CLI builds the .ino sketch → .bin
#   2. SHA256 hash generated
#   3. GitHub Release created with .bin attached
#   4. MQTT notification published → devices download + flash
#
# REQUIRED GITHUB SECRETS (repo → Settings → Secrets → Actions):
#   MQTT_BROKER    — your HiveMQ hostname (e.g., abc123.s1.eu.hivemq.cloud)
#   MQTT_PORT      — 8883
#   MQTT_USERNAME  — your HiveMQ username
#   MQTT_PASSWORD  — your HiveMQ password
#   MQTT_USE_TLS   — true

name: Build & Deploy OTA

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.2.0)'
        required: true
      target:
        description: 'Deploy target'
        required: true
        type: choice
        options:
          - fleet
          - canary
          - staging
          - production

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF_NAME#v}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building firmware v$VERSION"

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP8266 core & libraries
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls \
            https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

          # Install required libraries
          arduino-cli lib install "PubSubClient"
          arduino-cli lib install "ArduinoJson"

      - name: Inject version into config
        run: |
          # Add FIRMWARE_VERSION define before compilation
          sed -i 's/#define FIRMWARE_VERSION.*"1.0.0"/#define FIRMWARE_VERSION    "${{ steps.version.outputs.version }}"/' \
            esp8266_ota_firmware/config.h
          echo "Config after version injection:"
          grep FIRMWARE_VERSION esp8266_ota_firmware/config.h

      - name: Compile sketch
        run: |
          arduino-cli compile \
            --fqbn esp8266:esp8266:nodemcuv2 \
            --build-property "build.extra_flags=-DFIRMWARE_VERSION=\"${{ steps.version.outputs.version }}\"" \
            --output-dir ./build \
            esp8266_ota_firmware/

      - name: Prepare release artifacts
        id: artifacts
        run: |
          mkdir -p release

          # Find the .bin file
          cp build/esp8266_ota_firmware.ino.bin release/firmware.bin

          # SHA256
          SHA256=$(sha256sum release/firmware.bin | cut -d' ' -f1)
          echo "$SHA256" > release/firmware.sha256
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

          # Build info
          cat > release/build-info.json << EOF
          {
            "version": "${{ steps.version.outputs.version }}",
            "sha256": "$SHA256",
            "build_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "commit": "${{ github.sha }}",
            "size_bytes": $(stat -c%s release/firmware.bin)
          }
          EOF

          echo "✓ Build complete:"
          echo "  Version: ${{ steps.version.outputs.version }}"
          echo "  SHA256:  $SHA256"
          echo "  Size:    $(stat -c%s release/firmware.bin) bytes"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ steps.version.outputs.version }}
          path: release/

    outputs:
      version: ${{ steps.version.outputs.version }}
      sha256: ${{ steps.artifacts.outputs.sha256 }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware-${{ needs.build.outputs.version }}
          path: release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Firmware v${{ needs.build.outputs.version }}
          body: |
            ## Firmware v${{ needs.build.outputs.version }}

            **SHA256:** `${{ needs.build.outputs.sha256 }}`
            **Commit:** `${{ github.sha }}`

            ### OTA Update
            Devices will be notified via MQTT automatically.

            ### Manual trigger
            ```
            mosquitto_pub -h YOUR_BROKER -t "ota/fleet/all" \
              -m '{"version":"${{ needs.build.outputs.version }}","url":"https://github.com/${{ github.repository }}/releases/download/v${{ needs.build.outputs.version }}/firmware.bin","sha256":"${{ needs.build.outputs.sha256 }}"}'
            ```
          files: |
            release/firmware.bin
            release/firmware.sha256
            release/build-info.json

  notify:
    name: Notify Devices via MQTT
    needs: [build, release]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (for script)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install paho-mqtt
        run: pip install paho-mqtt

      - name: Publish MQTT OTA notification
        env:
          MQTT_BROKER:   ${{ secrets.MQTT_BROKER }}
          MQTT_PORT:     ${{ secrets.MQTT_PORT }}
          MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
          MQTT_USE_TLS:  ${{ secrets.MQTT_USE_TLS }}
        run: |
          python scripts/mqtt_notify.py \
            --version "${{ needs.build.outputs.version }}" \
            --sha256 "${{ needs.build.outputs.sha256 }}" \
            --repo "${{ github.repository }}" \
            --target "${{ github.event.inputs.target || 'fleet' }}"
